
language: swift
xcode_workspace: EosioSwiftiOSExampleApp.xcworkspace
xcode_scheme: EosioSwiftiOSExampleApp
osx_image: xcode10.1
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone X

matrix:
  - XCODE_VERSION='xcode10.2'
  - XCODE_VERSION='xcode10.1'

before_install:
- env
- gem install cocoapods -v 1.7.3
- pod repo update
- pod install
- wget https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/$VERACODE_WRAPPER_VERSION/vosp-api-wrappers-java-$VERACODE_WRAPPER_VERSION.jar

script:
- set -o pipefail 
- 'if ["$osx_image" == "10.1"]; then bash .scripts/veracode-scan.sh; fi'