language: swift
xcode_workspace: ArisenSwiftiOSExampleApp.xcworkspace
xcode_scheme: ArisenSwiftiOSExampleApp
osx_image: xcode10.2
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone X
before_install:
- env
- pod repo update
- pod install
script:
- set -o pipefail 
- xcodebuild -workspace ArisenSwiftiOSExampleApp.xcworkspace -scheme ArisenSwiftiOSExampleApp -destination platform\=iOS\ Simulator,OS\=12.0,name\=iPhone\ X build | xcpretty

